# Generated by Django 5.0.7 on 2024-11-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_articleelon_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleelon',
            name='files',
            field=models.FileField(default='1', upload_to='media/files', verbose_name='file yuklash'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articleelon',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='chop etish'),
        ),
    ]
