# Generated by Django 5.0.7 on 2024-11-13 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_articleelon_files_articleelon_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korupsiya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('img', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img1', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img2', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('img3', models.ImageField(upload_to='Photos/Yangiliklar/')),
                ('video', models.FileField(upload_to='Photos/Yangiliklar/')),
                ('publish_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publish_time'],
            },
        ),
    ]
