# Generated by Django 5.0.7 on 2024-11-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_korupsiya'),
    ]

    operations = [
        migrations.AddField(
            model_name='korupsiya',
            name='body_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='korupsiya',
            name='body_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='korupsiya',
            name='title_en',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='korupsiya',
            name='title_ru',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='korupsiya',
            name='video',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
