# Generated by Django 5.0.7 on 2024-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_korupsiya_body_en_korupsiya_body_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='korupsiya',
            name='video',
            field=models.CharField(default='ss', max_length=500),
            preserve_default=False,
        ),
    ]
